name: flutter_updater
description: Flutter updater.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.0-178.0.dev <3.0.0"

dependencies:
  args: ^2.2.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.4
