name: Release

on:
  release:
    types: [ published ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Flutter
        uses: hrishikesh-kadam/setup-flutter@v1

      - name: Build
        run: |
          dart pub get
          dart compile exe lib/main.dart --output ${{ github.workspace }}\updater.exe

      - name: Upload files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}\updater.exe
